import bcrypt from 'bcryptjs'

export const data = {
  users: [
    {
      name: 'ALejandro',
      email: 'naranjo.devel@gmail.com',
      password: bcrypt.hashSync('naranjo'),
      isAdmin: true,
    },
    {
      name: 'Nikol',
      email: 'nikolina@gmail.com',
      password: bcrypt.hashSync('nikol'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Fit_GRATIS',
      slug: 'FIt_GRATIS',
      category: 'freeshirt',
      image: '/images/shirt.jpg',
      price: 80,
      brand: 'MOnoktras',
      rating: 4.3,
      numReviews: 10,
      countInStock: 20,
      description: 'ea que camisota',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Comfort Bliss',
      slug: 'Comfort_Bliss',
      category: 'casualwear',
      image: '/images/casual_shirt.jpg',
      price: 65,
      brand: 'SereneStyle',
      rating: 4.8,
      numReviews: 15,
      countInStock: 25,
      description: 'Experience comfort like never before.',
      isFeatured: false,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Active Flex',
      slug: 'Active_Flex',
      category: 'sportswear',
      image: '/images/casual_shirt.jpg',
      price: 90,
      brand: 'FlexFit',
      rating: 4.5,
      numReviews: 12,
      countInStock: 18,
      description: 'Ideal for your active lifestyle.',
      isFeatured: true,
      banner: '/images/banner3.jpg',
    },
    {
      name: 'Chic Elegance',
      slug: 'ChicElegance',
      category: 'formalwear',
      image: '/images/casual_shirt.jpg',
      price: 120,
      brand: 'EleganceCloth',
      rating: 4.2,
      numReviews: 8,
      countInStock: 30,
      description: 'Elevate your style with chic elegance.',
      isFeatured: false,
      banner: '/images/banner4.jpg',
    },
    {
      name: 'Cozy Comfort',
      slug: 'CozyComfort',
      category: 'loungewear',
      image: '/images/casual_shirt.jpg',
      price: 75,
      brand: 'RelaxRays',
      rating: 4.6,
      numReviews: 20,
      countInStock: 22,
      description: 'Stay cozy and relaxed all day.',
      isFeatured: true,
      banner: '/images/banner5.jpg',
    },
    {
      name: 'Urban Swagger',
      slug: 'UrbanSwagger',
      category: 'streetwear',
      image: '/images/casual_shirt.jpg',
      price: 110,
      brand: 'CityVibe',
      rating: 4.4,
      numReviews: 18,
      countInStock: 28,
      description: 'Embrace the urban style with swagger.',
      isFeatured: false,
      banner: '/images/banner6.jpg',
    },
    {
      name: 'Vintage Charm',
      slug: 'VintageCharm',
      category: 'retrowear',
      image: '/images/casual_shirt.jpg',
      price: 95,
      brand: 'NostalgiaStyles',
      rating: 4.7,
      numReviews: 14,
      countInStock: 24,
      description: 'Bring back the charm of vintage fashion.',
      isFeatured: true,
      banner: '/images/banner7.jpg',
    },
    {
      name: 'Dapper Denim',
      slug: 'DapperDenim',
      category: 'denimwear',
      image: '/images/casual_shirt.jpg',
      price: 85,
      brand: 'DenimDeluxe',
      rating: 4.1,
      numReviews: 11,
      countInStock: 21,
      description: 'Look dapper in this stylish denim wear.',
      isFeatured: false,
      banner: '/images/banner8.jpg',
    },
    {
      name: 'Floral Fantasy',
      slug: 'FloralFantasy',
      category: 'summerwear',
      image: '/images/casual_shirt.jpg',
      price: 70,
      brand: 'BlossomBreeze',
      rating: 4.9,
      numReviews: 16,
      countInStock: 26,
      description: 'Step into a floral fantasy this summer.',
      isFeatured: true,
      banner: '/images/banner9.jpg',
    },
    {
      name: 'Tech Trend',
      slug: 'TechTrend',
      category: 'techwear',
      image: '/images/casual_shirt.jpg',
      price: 100,
      brand: 'InnovateGear',
      rating: 4.0,
      numReviews: 9,
      countInStock: 19,
      description: 'Embrace the future with tech-inspired fashion.',
      isFeatured: false,
      banner: '/images/banner10.jpg',
    },
  ],
}
